server:
  port: 9091

spring:
  application:
    name: chatterbox-user-service
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/users

logging:
  level:
    com.chatterbox.userservice: INFO